RoR - Private events associations project
Jmagero/private-events pull request #2
Opened 2020-09-10 21:43 UTC by guirecordon

### Collaborative project - Request for review
**We did the following for this project and now feel ready to request for a review. We: **

- created a User, an Event, and an EventManager model
- wrote the associations for them with their foreign keys and many-to-many relationships
- wrote validations for the users and event creators to be able to log in and only have access to their respective actions
- created a way for the users to be able to accept their invitations once they were made by another user. We did that by adding a 'confirmation' column to our EventManager table and only displaying the events once they were marked as true. They were all set to false in the beginning.
- we wrote integration tests and unit tests for authentication and models

thank you.

2020-09-10 23:15 UTC, mosesogwo requested changes
**Hello!:wave: Good start on this project:+1: Here are your required improvements:**

:point_right: Event's index page should display past and upcoming events lists. This isn't working right now. Events are not being displayed.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/past_upcoming_events_requirement.png)

:point_right: The event's show page displays the list of attendants. Attendants are not  being displayed currently.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png)

:point_right:  The user's show page displays events the user has created and events that the user is attending to separated in past and upcoming. The events are not visible on the page.

:point_right: Event model has an event date attribute. So you have to add the date attribute to your event creation form.

![](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)

:point_right: Events controller index action should list past and upcoming events. This grouping should be made in the controller and not views.

;point_right: Users controller show action should have the following:

```
lists events created by user, i.e. @created_events =  current_user.events (screenshot from Odin)

 lists events previoulsy attendented by user using event model scope, i.e. @past_events = current_user.attended_events.previous (screenshot from Odin)

 lists upcoming events previously attended by user using event model scope, i.e. @upcoming_events = current_user.attended_events.upcoming (screenshot from Odin)

```
:point_right: Event management feature spec should cover the entire event management feature. You should send an invite in your spec and verify that it's working.

:point_right: Your tests are failing. Please fix them.

_**Kindly make these changes and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

2020-09-14 16:05 UTC, guirecordon commented
Thank you, Moses.
We worked on the changes you requested. 

- The upcoming and past events should be working now
- Attendants of the events should also be displayed (we had to change the conditional for the invite accept in the users controller -- confirmed.zero?)
- The date attribute is working and we also added a couple of links, etc for better user experience.
- Finally, we seem to have been able to get the EventManager RSpec test to pass, but that was a tricky one. So we'd love to get some feedback on it.

We're requesting a new review.
Thank you

2020-09-14 18:31 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for applying the suggested changes
However, there are still some issues 

1. There are no information concerning the attended users, as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/events_attendees_requirement.png).
![Screenshot at 2020-09-14 19:09:50](https://user-images.githubusercontent.com/8848104/93122142-e5a0e480-f6bd-11ea-8490-374abb8b0f4f.png)
But if you take a look at the database, you will notice that there are invited users
```rb
2.7.1 :004 > EventManager.all
  EventManager Load (0.3ms)  SELECT  "event_managers".* FROM "event_managers" LIMIT ?  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<EventManager id: 1, attendee_id: 1, attended_event_id: 1, created_at: "2020-09-14 18:02:40", updated_at: "2020-09-14 18:02:40", confirmation: 0>, #<EventManager id: 2, attendee_id: 1, attended_event_id: 4, created_at: "2020-09-14 18:04:00", updated_at: "2020-09-14 18:04:00", confirmation: 0>]> 
2.7.1 :005 > Event.all
  Event Load (0.3ms)  SELECT  "events".* FROM "events" LIMIT ?  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<Event id: 1, name: "Music go", date: "2020-09-17 00:00:00", created_at: "2020-09-14 18:02:31", updated_at: "2020-09-14 18:02:31", creator_id: 1, description: "Yeah you are OK. https://github.com/emasdev/privat...">, #<Event id: 2, name: "Music go", date: "2020-09-01 00:00:00", created_at: "2020-09-14 18:02:50", updated_at: "2020-09-14 18:02:50", creator_id: 1, description: "Jour de ca ah bon!!!">, #<Event id: 3, name: "Pourrational high", date: "2020-09-30 00:00:00", created_at: "2020-09-14 18:03:22", updated_at: "2020-09-14 18:03:22", creator_id: 1, description: "Yeah you are OK. https://github.com/emasdev/privat...">, #<Event id: 4, name: "Reviewing", date: "2020-10-03 00:00:00", created_at: "2020-09-14 18:03:51", updated_at: "2020-09-14 18:03:51", creator_id: 2, description: "Read it correctly youre chaongre ;w;oijwe">]> 
```

2- There is no link to access to the user show page which is requested. [Check it here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_events_requirement.png)

3- The model `AddCreatorToEvent`  is never used. Can you remove it ?

4- Read the comments below

Kindly make the suggested changes and submit a new code review request
Thanks

Mael FOSSO

2020-09-14 18:31 UTC, maelfosso commented on app/views/users/show.html.erb
> +    <% end %>
Kindly remove login from views, move it in view helpers

2020-09-14 18:31 UTC, maelfosso commented on app/views/layouts/application.html.erb
> +    <% end %>
Move logic into view helpers

2020-09-14 18:31 UTC, maelfosso commented on app/views/events/index.html.erb
> +<% end %>
Move logic into view helpers

2020-09-14 18:31 UTC, maelfosso commented on app/views/events/show.html.erb
> +    <% end %>
Move logic into view helpers

2020-09-14 18:31 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    @previous_events = current_user.attended_events.where('date <= ?', DateTime.now)
No longer need to add request. You already have the scope `Event`.
Directly used
```rb
@upcoming_events = current_user.attended_events.upcoming
@previous_events = current_user.attended_events.past
```

2020-09-14 18:31 UTC, maelfosso commented on app/controllers/users_controller.rb
> +    end
No need to confirm the invitation!

2020-09-15 22:25 UTC, guirecordon commented
Thank you, Moses.

We removed all the logic from views and moved them to helpers; added the links you requested and made the other changes.

Thank you.

2020-09-15 23:00 UTC, Dandush03 approved these changes
# Status: :rocket: Approved :rocket: :smile: 
# Keep it up
# :computer: Happy Coding :computer:

2021-03-01 17:42 UTC, merged